version: '3.8'
services:

  portainer:
    image: portainer/portainer-ce:2.19.4
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: