# path:: mkdir -pv /data/volumes/mygits
# run:: docker compose -p memos --env-file ./builder/golang/env.cfg -f ./builder/golang/compose.yml up -d

services:

  golang:
    image: ${IMAGE_TAG_BASH}
    container_name: "build-golang"
    restart: always
    tty: true
    command: bash
    volumes:
      - ${Volumes_Path}/mygits:/app
    working_dir: /app
    environment:
      - GOPROXY=https://goproxy.cn
      - GO111MODULE=on