# Pull: docker compose -p valkey --env-file ./base/redis/env.cfg -f ./base/redis/valkey.stack.yml pull

# Run:: docker compose -p valkey --env-file ./base/redis/env.cfg -f ./base/redis/valkey.stack.yml up -d
services:
  redis:
    image: ${IMAGE_TAG_VALKEYV8}
    ports:
      - '6379:6379'
    command: valkey-server --appendonly yes
    volumes:
      - '${Volumes_PATH}/redis:/data'