# docker compose p it-tools -f it-tools/compose.yml up -d
version: "3.9"
services:

  it-tools:
    image: corentinth/it-tools:2023.12.21-5ed3693
    restart: unless-stopped
    ports:
      - "8380:80"