# docker compose -p dbs -f ./dev-dbs/dbs.networks.set.yml -f ./dev-dbs/postgres.yml pull
# docker compose -p dbs -f ./dev-dbs/dbs.networks.set.yml -f ./dev-dbs/postgres.yml up -d
services:

  postgres:
    image: postgres:15.6-bookworm
    container_name: Dev-postgre
    restart: always
    environment:
      - POSTGRES_PASSWORD=Kevin%0412&PGSql
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      DevNet:
        ipv4_address: 172.22.10.208

volumes:
  postgresql_data: