# mkdir -pv /data/volumes/gitea/{data,config}
# cd gitea by lcayun
# chown 1000:1000 config/ data/
# pull:: docker compose --env-file ./gitea/env.cfg -f ./gitea/lky-prod.yml up pull
# RUN:: docker compose -p gitea --env-file ./gitea/env.cfg -f ./gitea/lky-prod.yml up -d

services:

  gitea:
    image: ${IMAGE_TAG}
    restart: always
    container_name: gitea-app
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${Volumes_PATH}/data:/var/lib/gitea
      - ${Volumes_PATH}/config:/etc/gitea
    ports:
      - 3000:3000
      - ${LAY_SSH_HOST_PORT}:2222