# mkdir -pv gitea/{data,config}
# cd gitea
# chown 1000:1000 config/ data/
# pull:: docker compose --env-file ./gitea/env.cfg -f ./gitea/stack.yml pull
# Run:: docker compose -p gitea --env-file ./gitea/env.cfg -f ./gitea/stack.yml up -d
version: "3.9"

services:

  gitea:
    image: ${IMAGE_TAG}
    restart: always
    container_name: gitea-app
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ${Volumes_PATH}/data:/var/lib/gitea
      - ${Volumes_PATH}/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 2222:2222
