# mkdir -pv /data/volumes/ocis/{config,data}
# chown -R 1000:1000 /data/volumes/ocis
# pull:: docker compose -p owncloud -f ./nextcloud/owncloud.ocis.yml pull
# init:: docker run --rm -it -v /data/volumes/ocis/config:/etc/ocis owncloud/ocis init
# docker compose -p owncloud -f ./nextcloud/owncloud.ocis.yml up -d
version: '3.9'
services:

  ocis:
    image: owncloud/ocis:latest
    environment:
      - 'OCIS_URL=https://192.168.10.200:9200'
      - 'PROXY_HTTP_ADDR=0.0.0.0:9200'
      - OCIS_INSECURE=true
    volumes:
      - /data/volumes/ocis/data:/var/lib/ocis
      - /data/volumes/ocis/config:/etc/ocis
    ports:
      - '9200:9200'
    restart: unless-stopped