#pull:: docker compose --env-file ./dbSer/postgres/env.cfg -f ./dbSer/postgres/test.prod.stack.yml pull
#run::  docker compose -p test-dbs  --env-file ./dbSer/postgres/env.cfg -f ./dbSer/postgres/test.prod.stack.yml up -d

services:

  postgres:
    image: ${IMAGE_TAG}
    container_name: prod-postgre
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_INITDB_ARGS=--auth-host==${POSTGRES_HOST_AUTH_METHOD}
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - TZ=Asia/Shanghai
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data: