version: "3.8"
services:

  sealms:
    image: hub.local:3500/cnphpbb/alpine-cn:3.12
    restart: always
    volumes:
      - "/data/www-root/seal-ms/sealms/release:/app"
    command: "/app/start.sh"
    networks:
      DevNet:
        ipv4_address: 172.23.23.21
    ports:
      - "2975:2975"

  sealms-ui:
    image: hub.local:3500/cnphpbb/caddy:2-alpine
    restart: always
    volumes:
      - "/data/www-root/seal-ms/sealms-ui:/app"
      - "/data/deploy/configs/caddy/sealms-ui.conf:/etc/caddy/Caddyfile"
    networks:
      DevNet:
        ipv4_address: 172.23.23.11
    ports:
      - "8008:8008"



networks:
  DevNet:
    name: DevNet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.23.0/24