# path:: mkdir -pv /data/volumes/tasks.md/{tasks,config}
# pull:: docker compose -p memos --env-file ./tasks.md/env.cfg -f ./tasks.md/stack.yml pull
# run:: docker compose -p memos --env-file ./tasks.md/env.cfg -f ./tasks.md/stack.yml up -d

services:
  tasks.md:
    image: ${IMAGE_TAG}
    container_name: tasks.md
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${Volumes_Path}/tasks:/tasks
      - ${Volumes_Path}/config:/config
    restart: unless-stopped
    ports:
      - 5480:8080