# mkdir -pv /data1/volumes/alist/{data,localFS}
# pull:: docker compose --env-file ./alist/env.yml -f ./alist/compose.yml pull
# run:: docker compose -p alist --env-file ./alist/env.yml -f ./alist/compose.yml up -d
## 随机生成一个密码
# docker exec -it alist-alist-1 ./alist admin random
version: '3.9'
services:
  alist:
    image: ${IMAGE_TAG}
    volumes:
      - $DATA_PATH:/opt/alist/data
      - $LOCALFS_PATH:/data
    ports:
      - '5244:5244'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: unless-stopped