# run:: docker compose -p memos -f ./memos/local.yml up -d

services:
  memos:
    image: neosmemo/memos:0.20.0
    #command: '--driver mysql --dsn root:Kevin%0412%Mysql@tcp(10.10.13.233:3306)/memos-db'
    volumes:
      - data:/var/opt/memos
    ports:
      - '5230:5230'
    container_name: memos
    environment:
      - MEMOS_DRIVER=postgres
      - MEMOS_DSN=postgresql://postgres:Kevin0412PgSql@10.10.13.233:5432/memos-db?sslmode=disable
      - TZ=Asia/Shanghai

volumes:
  data: