services:
  percona:
    image: percona:8.0.35-27
    container_name: Dev-Percona
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Kevin#0412&Mysql
    volumes:
      - percona_data:/var/lib/mysql
      - percona_logs:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      DevNet:
        ipv4_address: 172.22.10.206

volumes:
  percona_data:
  percona_logs: